/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicQuotationPreviewRouteImport } from './routes/_public.quotation-preview'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicEstimateRouteImport } from './routes/_public.estimate'
import { Route as PublicContactRouteImport } from './routes/_public.contact'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicQuotationPreviewRoute = PublicQuotationPreviewRouteImport.update({
  id: '/quotation-preview',
  path: '/quotation-preview',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEstimateRoute = PublicEstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/contact': typeof PublicContactRoute
  '/estimate': typeof PublicEstimateRoute
  '/pricing': typeof PublicPricingRoute
  '/quotation-preview': typeof PublicQuotationPreviewRoute
  '/services': typeof PublicServicesRoute
}
export interface FileRoutesByTo {
  '/contact': typeof PublicContactRoute
  '/estimate': typeof PublicEstimateRoute
  '/pricing': typeof PublicPricingRoute
  '/quotation-preview': typeof PublicQuotationPreviewRoute
  '/services': typeof PublicServicesRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/estimate': typeof PublicEstimateRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/quotation-preview': typeof PublicQuotationPreviewRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/estimate'
    | '/pricing'
    | '/quotation-preview'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/estimate'
    | '/pricing'
    | '/quotation-preview'
    | '/services'
    | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/contact'
    | '/_public/estimate'
    | '/_public/pricing'
    | '/_public/quotation-preview'
    | '/_public/services'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/quotation-preview': {
      id: '/_public/quotation-preview'
      path: '/quotation-preview'
      fullPath: '/quotation-preview'
      preLoaderRoute: typeof PublicQuotationPreviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/estimate': {
      id: '/_public/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof PublicEstimateRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicEstimateRoute: typeof PublicEstimateRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicQuotationPreviewRoute: typeof PublicQuotationPreviewRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicEstimateRoute: PublicEstimateRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicQuotationPreviewRoute: PublicQuotationPreviewRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
