/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicEstimateRouteImport } from './routes/_public.estimate'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEstimateRoute = PublicEstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/estimate': typeof PublicEstimateRoute
  '/pricing': typeof PublicPricingRoute
  '/services': typeof PublicServicesRoute
}
export interface FileRoutesByTo {
  '/estimate': typeof PublicEstimateRoute
  '/pricing': typeof PublicPricingRoute
  '/services': typeof PublicServicesRoute
  '/': typeof PublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/estimate': typeof PublicEstimateRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/': typeof PublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estimate' | '/pricing' | '/services'
  fileRoutesByTo: FileRoutesByTo
  to: '/estimate' | '/pricing' | '/services' | '/'
  id:
    | '__root__'
    | '/_public'
    | '/_public/estimate'
    | '/_public/pricing'
    | '/_public/services'
    | '/_public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/estimate': {
      id: '/_public/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof PublicEstimateRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicEstimateRoute: typeof PublicEstimateRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicEstimateRoute: PublicEstimateRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
